
spring:
  datasource:
    # 配置数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.andu.club:3306/message?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: message
    password: 1234
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j
# Socket配置
socket:
  # 监听端口 2323
  port: 8866
  # 线程池 - 保持线程数 20
  pool-keep: 20
  # 线程池 - 核心线程数 10
  pool-core: 10
  # 线程池 - 最大线程数 20
  pool-max: 30
  # 线程队列容量 10
  pool-queue-init: 10
server:
  port: 80
